[WIP] Fix building with crossbuilder
ubports/indicator-display pull request #1
Opened 2018-10-06 13:19 UTC by jonnius

2018-10-06 13:22 UTC, jonnius commented
I tried to disable the tests as @mardy proposed for the messaging app. But I get:
```
dh build --with translations \
        -DENABLE_TESTS=OFF
   dh_testdir -O-DENABLE_TESTS=OFF
   dh_update_autotools_config -O-DENABLE_TESTS=OFF
   dh_auto_configure -O-DENABLE_TESTS=OFF
dh_auto_configure: invalid or non-existing path to the source directory: ENABLE_TESTS=OFF
debian/rules:8: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```
Do I need to split those dh_* calls as it is done in the messaging app?

2018-10-12 19:01 UTC, mardy requested changes

2018-10-12 19:01 UTC, mardy commented on debian/control
>                 gsettings-ubuntu-schemas (>= 0.0.2+14.10.20140813),
Please add `<!nocheck>` also to `libqtdbustest1-dev`, `libgtest-dev` and `google-mock`

2018-10-12 19:01 UTC, mardy commented on debian/rules
> +	        $(CONFIGURE_OPTS)
By doing so, you are passing the `$(CONFIGURE_OPTS)` to every step of the build, while you need to pass them only to the `auto_configure` one. See the second answer from https://superuser.com/questions/250437/how-to-pass-custom-options-to-configure-when-building-a-package-with-debuild :-)

2018-10-12 19:01 UTC, mardy commented on debian/rules
> +	        $(CONFIGURE_OPTS)
Or you can try with `DEB_CONFIGURE_EXTRA_FLAGS` as explained [here](https://wiki.debian.org/Multiarch/Implementation).

2018-10-13 20:26 UTC, mardy commented on debian/rules
> +	        $(CONFIGURE_OPTS)
Forget about the `DEB_CONFIGURE_EXTRA_FLAGS` thing, it looks like it doesn't actually exist. Feel free to continue using `CONFIGURE_OPTS` :-)

2018-10-14 19:15 UTC, jonnius commented on debian/control
>                 gsettings-ubuntu-schemas (>= 0.0.2+14.10.20140813),
Done

2018-10-14 19:15 UTC, jonnius commented on debian/rules
> +	        $(CONFIGURE_OPTS)
Done

2018-10-14 19:17 UTC, jonnius commented
Thanks again for your help!

2018-10-14 19:18 UTC, mardy approved these changes
Excellent, thanks!

2018-10-14 19:18 UTC, merged